### ISSUE TITLE
Support viewport resize

### ISSUE THREAD

**Issue by dzikoysk** [HJ29/vue3-tabs#3]
At this moment, during the resize of viewport, the whole tab system goes wild:

![2021-04-30_01-40-30](https://user-images.githubusercontent.com/4235722/116631415-5b0fab80-a955-11eb-809f-5a993c543ddc.gif)

It could be great if there would be a possibility to somehow handle this scenario.

**Comment by dzikoysk** [comment]
@HJ29 Do you have any plans related to this issue? It's quite braking and as I'm going back to the project where I'm using this library, I need to know if it's abandoned at this point. I understand you may not have enough time to play with it, so it's just good to make a statement about it - to let people know if they should just move to an alternative library in such a case :)

**Comment by HJ29** [comment]
i just fixed the issue in v0.1.12, if u are still using it, try it out in [demo](https://hj29.github.io/vue3-tabs/).

sorry for the inconvenience caused.

**Comment by dzikoysk** [comment]
Thanks and good job! I can confirm that it works properly now :)
